apiVersion: v1
kind: Service
metadata:
  name: verifier-service
  namespace: verifier-system
spec:
  selector:
    app: verifier-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 50051
  type: ClusterIP